services:
  cash_register_1:
    build: .
    container_name: cash_register_1
    command: node app.js
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: hello1234
      DB_NAME: shop_db

  cash_register_2:
    build: .
    container_name: cash_register_2
    command: node app.js
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: hello1234
      DB_NAME: shop_db

  cash_register_3:
    build: .
    container_name: cash_register_3
    command: node app.js
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: hello1234
      DB_NAME: shop_db

  database:
    image: mysql:latest
    container_name: shop-db-container
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: hello1234
      MYSQL_DATABASE: shop_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
    db_data: