
services:
  app:
    build: .
    container_name: shop-app
    command: node app.js
  server:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_USER: sirine
      MYSQL_ROOT_PASSWORD: hello1234
      MYSQL_DATABASE: shop_db